######################################################################
# Automatically generated by qmake (3.0) ?? 12? 20 17:14:21 2016
######################################################################

TEMPLATE = app
TARGET = LabelUI
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
